# Generated by Django 5.0.3 on 2024-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
